### PR TITLE
Multicall via Ethcall

### PR DESCRIPTION
**Pull request by aboutlo**
related to #17 
Batching the transaction by using `EthCall` lib which uses `multiCall` contract.

### CODE REVIEW

**Comment by aboutlo** [comment]
Also, it drops the requirement to pass the signer to the fetcher.
it's a breaking change but it should fix #13

**Comment by jviray** [comment]
@aboutlo I'm getting this error message for all calls using useEtherSWR:
 
```
JsonRpcEngine: Response has no error or result for request: ...
```

Here's an example of the call I made. This worked previously with the useEtherSWR hook:

```
const { data: addressFromRegistry, error } = useEtherSWR(
  [
    '0x7EC81B7035e91f8435BdEb2787DCBd51116Ad303',
    'getAddress',
    bytes32('usdcDemoPool'),
  ],
  { ABIs: new Map(REGISTRY_ABIS) }
);
```

Btw, I'm testing it out through a forked version with this pr merged

**Comment by aboutlo** [comment]
Looks like `etherjs` isn't happy about   `{ blockTag: null }`. Can you try:
- remove it 
- change it to `{ blockTag: '' }`
- change it  `{ blockTag: VALID_BLOCK} }`
- you can try to reproduce with a test here: https://github.com/aboutlo/ether-swr/blob/5bb0b31c9ccbba32dd1ce392516c058aea2f75ba/test/integration/fetcher.test.tsx#L58

I will try to have a look later

**Comment by jviray** [comment]
> Looks like `etherjs` isn't happy about `{ blockTag: null }`. Can you try:
> 
> * remove it
> * change it to `{ blockTag: '' }`
> * change it  `{ blockTag: VALID_BLOCK} }`


Removing the entire options object worked (returned without any error), although I do need to be able to use that options obj to set the blockTag.

```
[address1, 'getPoolTotalValue']
```

But the other options returned a similar error. Tried all of these:

- [address1, 'getPoolTotalValue', { blockTag: '' }]
- [address1, 'getPoolTotalValue', { blockTag: CURRENT_BLOCK }]
- address1, 'getPoolTotalValue', { blockTag: undefined }]

**Comment by aboutlo** [comment]
I looked in ethcall and they handle `blockTag` differently.  I'm looking to extract it from the args and pass it to ethcall as it expects 🤞

**Comment by aboutlo** [comment]
https://github.com/Destiner/ethcall/blob/cf8de6f11361b6fa88c3ee84cad020baf7744d35/src/call.ts#L41 

basically, all the calls have the same block when you use the multicall contract.

**Comment by jviray** [comment]
Looks like multicall solutions generally will override the block to prevent errors from batched calls with mixed blockTags. This library will skip aggregation and execute the calls individually if there are mixed blockTags. 

https://github.com/0xsequence/sequence.js/tree/master/packages/multicall

I also found this package which looks very similar to ethcall.

https://github.com/cavanmflynn/ethers-multicall

In this PR they add the blockTag option. But it has yet to be merged.
https://github.com/cavanmflynn/ethers-multicall/pull/8/commits/ea8e6e59a5e7b478bd8764e9cfe896597225fc1a

**Comment by aboutlo** [comment]
Now it works with the `blockTag` too but it doesn't split calls in case the block tag is different. 
Here is the important bit: https://github.com/aboutlo/ether-swr/blob/4f2a60fe806b2d6395ddfafe9d9b0b0b730561a1/src/ether-js-fetcher.ts#L26-L40

I need to think a bit more about throwing vs overriding. If you asked for a specific block seems better to tell you I can't do it. However, I need to double-check if SWR shallows the exceptions from the fetcher or not because otherwise is pointless and it's better to override. 

I will have a look at https://github.com/0xsequence/sequence.js/tree/master/packages/multicall perhaps isn't too much work to pick that one but not ideal doing twice :)

**Pull request closed without merging**
